### ISSUE TITLE
Nested Items Bug

### ISSUE THREAD

**Issue by Jscott388** [Soluto/graphql-to-mongodb#13]
```
{
  properties(filter: {
    SystemID: {EQ: 457397}
    Photos: {
      Sequence: {
        EQ: 0
      }
    }
  }
  ) {
    _id
    Photos {
      Sequence
    }
  }
}
```
Photos is part of another GraphQLObjectType as I don't know of a way to have nested fields.

```
export default new GraphQLObjectType({
  name: 'Photos',
  fields: {
    MediaID: { type: GraphQLInt },
    MediaTypeID: { type: GraphQLInt },
    Sequence: { type: GraphQLInt },
    MediaUrl: { type: GraphQLString },
    Caption: { type: GraphQLString },
    Description: { type: GraphQLString },
    FileSize: { type: GraphQLInt },
    Width: { type: GraphQLInt },
    Height: { type: GraphQLInt },
    Duration: { type: GraphQLInt },
    CreateDate: { type: GraphQLString },
    UpdateDate: { type: GraphQLString },
  },
});
```
My Properties: 

```
export default new GraphQLObjectType({
  name: 'Property',
  fields: {
    _id: {
      type: new GraphQLNonNull(GraphQLID)
    },
    SystemID: { type: GraphQLInt },
    Class: { type: GraphQLString },
    PropertyType: { type: GraphQLString },
    Area: { type: GraphQLString },
    SearchPrice: { type: GraphQLInt },
    ListingPrice: { type: GraphQLInt },
    AddressNumber: { type: GraphQLString },
   ...... more fields between .....
    DocTimestamp: { type: GraphQLString },
    Photos: { 
      type: GraphQLList(photoType),
    },
  },
});
```
So filter will auto populate the Photos. Sort will not. While you can populate the field, the filter operations doesn't work. It will return everything in the array. 

I don't know if this was intended or not. I was looking to sort out my Photos and/or filter them being a nested object. 

The photos are embedded into the Mongodb document itself, so they aren't in a separate collection. I was trying to save from having to make multiple calls to each of the properties for photos. Meaning I have over 3,000 property listings. So that would have to return 3,000 database calls to grab the photo without caching / data loader. 

On my listings page, I only wanted to return the photo with sequence 0, on the details page, I want to return only the single property, with all the photos to that property. (real estate project). 

I supposed I could use a different method of handling this, but the issue to report here, is FILTER will  auto populate the nested list, no errors. Sort will not auto populate the nested list.

**Comment by yoavkarako** [comment]
1. That is how you should define nested fields
2. I might be missing something, but what's stopping you from querying all 3000 properties in a single call using the `IN` operator? (Aside from DB constraints on the size of the filter document) i.e.:
```
{
  properties(filter: {
    SystemID: {IN: [457397,457396,...]}
    Photos: {
      Sequence: {
        EQ: 0
      }
    }
  }
  ) {
    _id
    Photos {
      Sequence
    }
  }
}
```
3. The filter is intended to work this way. i.e., Your filter will return all document in which the `Photos` array contains an object with a `Sequence` of 0. It doesn't have anything to do with what part of the document MongoDB populates.
MongoDB has limited functionality in terms of [projecting only part of an embedded array](https://docs.mongodb.com/manual/reference/operator/projection/elemMatch/).
Add to that the [substantial limitations](https://docs.mongodb.com/manual/reference/operator/projection/positional/#array-field-limitation) imposed over this functionality, its prioritization is low on possible additions to the package.
4. Similarly, `sort` will not affect the internal array, but the order of the documents being retrieved from MongoDB
5. To the best of my knowledge, neither `filter` nor `sort` have anything to do with what parts of the document MongoDB populates. That is decided by the `projection` object, which the package calculates from the fields you request in your query. e.g.
```
{
  _id
  Photos {
    Sequence
  }
}
=>
{
"_id": 1,
"Photos.Sequence": 1
}
```
Will populate the `_id` field and every item in the `Photos` array with only its `Sequence` field.

Taking that explanation into consideration, could you please recheck the conclusion you reached regarding the effects of `sort` and `filter` on document fields\` population?
Please add logs of the `filter`,`sort`, and `projection` objects if the unexpected behavior persists, i.e., the `Photos` array being populated without being specified in the query, or `Photos` array not being populated when being specified in the query.

**Comment by Jscott388** [comment]
I had to separate my photos in another collection do to how the data is fetched. In real estate data, the properties doesn't contain the photos. I was trying to embed the photos in array but when it comes to updating the photos, it was little more difficult due to the way real estate data works.

That being said this is the trouble I am having. 

```
{
  properties(
    filter: {
    Class: {
      EQ: "RESIDENTIAL"
    }
  },
    pagination: {limit: 25, skip: 0}) {
    _id
    Class
    Bedrooms
    Bathrooms
    Photos {
      MediaUrl
    }
  }
}
```

Returns 

```
{
  "data": {
    "properties": [
      {
        "_id": "361762",
        "Class": "RESIDENTIAL",
        "Bedrooms": 3,
        "Bathrooms": 1,
        "Photos": []
      },
      {
        "_id": "417569",
        "Class": "RESIDENTIAL",
        "Bedrooms": 3,
        "Bathrooms": 2,
        "Photos": []
      },
      {
        "_id": "390822",
        "Class": "RESIDENTIAL",
        "Bedrooms": 2,
        "Bathrooms": 2,
        "Photos": []
      },
..... more results
```

This is not intended to return a empty array of photos. 

Removing the filter will return the array of photos. So how can I still apply filters and return my array of photos?

**Comment by yoavkarako** [comment]
Can you add the code for your GraphQL type, specifically the `Photos` field's resolve function?
