### ISSUE TITLE
Example using Apollo?

### ISSUE THREAD

**Issue by thardy** [Soluto/graphql-to-mongodb#25]
I'm new to graphQL and got the simplest server up and running, but I've been trying to get the Apollo server working because I want to use GraphQLPlayground instead of GraphIQL - https://github.com/apollographql/apollo-server.

Do you guys have an example of graphql-to-mongodb working with the Apollo server?  I'm having some trouble getting the two to play nicely together.

**Comment by thardy** [comment]
I got the basic Apollo server working with GraphQLPlayground.  I'll post a repo once I get graphql-to-mongodb working in my prototype as well.

**Comment by MassiAtHG** [comment]
Any news on this @thardy? Very interested seeing this integration work.
