### ISSUE TITLE
Limit and Skip not working

### ISSUE THREAD

**Issue by Jscott388** [Soluto/graphql-to-mongodb#3]
```
export default {
  type: new GraphQLList(propertyType),
  args: getGraphQLQueryArgs(propertyType),
  resolve: getMongoDbQueryResolver(
    propertyType,
    async (filter, projection, options, obj, args, context) => {
      console.log(filter);
      console.log(projection);
      console.log(options);
      
      return await db.collection('properties').find(filter, projection, options).toArray();
    }
  )
};
```

What console.log gives

```
{ Class: { '$eq': 'RESIDENTIAL' } }
{ _id: 1, City: 1, Class: 1 }
{ sort: { _id: 1 }, limit: 5, skip: 5 }

```

What my query is:

```
query{
  properties(
    filter: {
      Class: {EQ: "RESIDENTIAL"}
    },
    sort: {_id: ASC},
    pagination: { limit: 5, skip: 5 }
  ) {
    _id
    City
    Class
  }
}
```

I get everything back. I have well over 1000+ records.

**Comment by Jscott388** [comment]
`return await db.collection('properties').find(filter, projection, options).limit(options.limit).skip(options.skip)toArray();`

This works.

**Comment by soluto-yoav** [comment]
Hello @Jscott388, and thanks for the feedback!
I suspect this is an issue with API difference between MongoDB driver versions.
I'd appreciate it if you could share the version of the `mongodb` package you're using in your project.

**Comment by Jscott388** [comment]
mongodb: "^3.0.5"

Node

I am using Mongodb Atlas so this is why I am using this driver.

**Comment by soluto-yoav** [comment]
As of 3.0, the `find` function __accepts only two arguments__. `projection` goes in the `options` object. 

That means that In the above-mentioned solution, projection and sorting aren't working.

A simple workaround until a version of the package aimed at latest driver API is released:
```
options.projection = projection;
return await db.collection('properties').find(filter, options).toArray();
```
