### ISSUE TITLE
Example usage of OR and AND?

### ISSUE THREAD

**Issue by thardy** [Soluto/graphql-to-mongodb#30]
I'm trying to figure out the syntax for using OR and AND in queries.  Do you have a simple example?

**Comment by yoavkarako** [comment]
Using the object types presented in the README, you could do something like this:
```
{
    person (
        filter: {
            OR: [{
                age: { GT: 18 },
                name: {  firstName: { EQ: "John" }  }
            }, {
                name: {  firstName: { NEQ: "John" }  }
            }]
        }
    ) {
        fullName
        age
    }
}
```
Which would retrieve those who match either: 
A. Are over the age of 18 and whose first name is John.
OR
B. Whose first name is not John.

The AND syntax is identical.

**Comment by thardy** [comment]
Exactly what I was looking for.  Thanks.
