### ISSUE TITLE
How to use mutations?

### ISSUE THREAD

**Issue by ernesto-pm** [Soluto/graphql-to-mongodb#33]
Any chance you can give an example on how to use mutations? such as insert, create, etc

**Comment by yoavkarako** [comment]
Issue https://github.com/Soluto/graphql-to-mongodb/issues/4 addressed this.

**Comment by hisuwh** [comment]
Issue #4 doesn't address how to call the update methods from graphql query

**Comment by yoavkarako** [comment]
Hi @hisuwh. If you haven't yet, you could read the GraphQL introduction for [mutations](https://graphql.org/learn/queries/#mutations).

Also, here is a basic example of a mutation that may be called to any of the package's [examples](https://github.com/Soluto/graphql-to-mongodb/blob/master/examples) (Use of variables was omitted for simplicity's sake):
```
mutation {
  insertPerson (input: {
    age: 25,
    name: {
      first: "John",
      last: "Doe"
    }
  })
}
```

**Comment by hisuwh** [comment]
thanks @yoavkarako 
This is an insert and my question was about updating an existing record.  My problem was specifically that i was trying to update by id which I could not get to work.

I.e.

```gql
mutation {
  updatePerson(
    filter: {
      _id: { EQ: "321564546" }
    }
    update: {
      set: {
        age: 27
      }
    }
  )
}
```

I was able to get an update working filtering on something else.  But ideally I would want more assurance that I am updating the right record by using the id.
