### ISSUE TITLE
Insert implementation?

### ISSUE THREAD

**Issue by ShynRou** [Soluto/graphql-to-mongodb#4]
Hey,

Is there an implementation for inserts? 
Yes? Could you show an example?
No? Should I take a shot at it?

Otherwise it works quite well so far :)

**Comment by soluto-yoav** [comment]
Hi,

Thanks for the interest and willingness to contribute.
There is currently an implementation for inserts and updates.

The suggested insert implementation is pretty simplistic at the moment, and relies mostly on `getGraphQLInsertType`:
```
insertPeople: {
    type: GraphQLString,
    args: {
        items: { type: new GraphQLNonNull(new GraphQLList(getGraphQLInsertType(PersonType))) }
    },
    resolve: async (obj, args, context) => {
        await context.db.collection('persons').insert(args.items);
        return 'success';
    }
}
```

Updates are more similar to queries, but are also more open to interpretation.
They work with `getGraphQLUpdateArgs` and `getMongoDbUpdateResolver`.
With the filter param, you can retrieve the documents you just updated, but it requires an additional query:
```
updatePeople: {
    type: new GraphQLList(PersonType),
    args: getGraphQLUpdateArgs(PersonType),
    resolve: getMongoDbUpdateResolver(PersonType,
        async (filter, update, options, projection, obj, args, context) => {
            await context.db.collection('persons').update(filter, update, options);
            return await context.db.collection('persons').find(filter, projection, options).toArray();
        }
    )
}
```
Or, you could just return a return a simplistic result like in the insert example, as there's no constraint on type:
```
updatePeople: {
    type: GraphQLString,
    args: getGraphQLUpdateArgs(PersonType),
    resolve: getMongoDbUpdateResolver(PersonType,
        async (filter, update, options, projection, obj, args, context) => {
            await context.db.collection('persons').update(filter, update, options);
            return 'success';
        }
    )
}
```

A possible improvement to consider could be to add [mongodb update writeresults](https://docs.mongodb.com/manual/reference/method/db.collection.update/#writeresults-update) as a GraphQL type in the package and return it... Maybe incorporate it in the `getMongoDbUpdateResolver` to check for faliures...

And expansion of the documentation will be added at a later date.

**Comment by ShynRou** [comment]
Thanks for the detailed answer! :+1: 

I would suggest 2 functions for the insert to make it a bit simpler:

getGraphQLInsertOneArgs(PersonType)
``` graphql
mutation {
  insertPerson(name: "Amy"){
    ok
  }
}
```

getGraphQLInsertManyArgs(PersonType)
``` graphql
mutation {
  insertPeople(items: [{name: "Amy"}, {name: "Bruce"}]){
    ok
  }
}
```

Sadly GraphQL doesn't support a direct array as input. It would make more sense in my opinion.
