### ISSUE TITLE
Does graphql-to-mongodb handle relationships?

### ISSUE THREAD

**Issue by thardy** [Soluto/graphql-to-mongodb#44]
Before I dig too deep, I was wondering if this library supports simple relationships, like a book with an authorId - can I pull an author object back on a book query?

Also, is there a better place to ask questions like this that aren't issues?  I couldn't find anything on Stackoverflow.  Do you guys have a gitter room, slack room, or forum?

**Comment by yoavkarako** [comment]
The library does not provide any way to describe relationships, nor will it make any guesswork to try and retrieve the related objects for you. However, it does not impede you from extending your type with a field to perform such a query.

A naive implementation of a book type that could be added to the [express example](https://github.com/Soluto/graphql-to-mongodb/blob/master/examples/express/src/schema.ts) to play with:
```
const BookType = new GraphQLObjectType({
    name: 'BookType',
    fields: () => ({
        name: { type: GraphQLString },
        pages: { type: GraphQLInt },
        authorId: { type: GraphQLID },
        author: { 
            type: PersonType,
            resolve: async (obj, args, { db }: { db: Db }, info) => {
                if (!obj.authorId) return null;
                const projection = getMongoDbProjection(info, PersonType);
                return await db.collection("people").findOne({ _id: new ObjectId(obj.authorId) }, { projection })
            },
            dependencies: ['authorId']
        }
    })
});
```
Note that you can still use the library to get an exact projection. I imagine a more mature solution will use a [batching](https://github.com/graphql/dataloader#batching) solution to ensure minimal DB queries.

There isn't a place to ask these kinds of questions at present besides here.
