### ISSUE TITLE
How to use it with type-graphql

### ISSUE THREAD

**Issue by georgyfarniev** [Soluto/graphql-to-mongodb#45]
Hello. First of all, thank you very much for creating this useful library. I would like to know how can I use this library with type-graphql? More precisely, I don't know where I can find second argument for **getMongoDbProjection**. As I understand, it's generated by type-graphql under the hood.

Everything I need is just to create projection from GraphQL query info.

Thanks.

**Comment by yoavkarako** [comment]
Hi,

This library is in no way reliant on `type-graphql`.

The second argument `graphQLFieldsType: GraphQLFieldsType` type is defined as `export type GraphQLFieldsType = GraphQLObjectType | GraphQLInterfaceType`. `GraphQLObjectType` and `GraphQLInterfaceType` are both part of the `graphql`package.
You should pass in the GraphQL type of the field you're creating the projection for.

I'm glad people find the library useful.
