### ISSUE TITLE
How to ingrate this with a .graphql schema file?

### ISSUE THREAD

**Issue by GimignanoF** [Soluto/graphql-to-mongodb#55]
I'm trying to integrate this package into an existing NodeJS service wich has the schema definition written in some .graphql files. However i'm having some troubles making the resolvers run :/ I've setup a small example project wich describe the actual situation I'm facing, you can find the repository here
```
https://github.com/GimignanoF/GraphQLFilters
```

Essentially i have setup two queries. One is using the approach I'm currently using, wich works just fine. The other one tries to use this package, however when i run that query i get this error as GraphQL result

```
Expected Iterable, but did not find one for field RootQuery.pages.
```

So, is there any way I can use this package in this scenario? Or should i rewrote the entire schema (wich is quite big) in the source code, rather then parsing it from the .graphql files?

**Comment by yoavkarako** [comment]
You can parse a GQL schema written in the SDL (your .graphql file), but you'll need to add directives over the field that would usually have the middleware applied to instead.
I suggest you look at the package's [graphql-tools example](https://github.com/Soluto/graphql-to-mongodb/tree/master/examples/graphql-tools). Feel free to ask for further elaboration after.

**Comment by GimignanoF** [comment]
Thank you for the answer, I looked at that package already, but then I found the graphql-compose-mongoose package, wich is good since I'm using MongoDB :) Thank you anyway for the help :)
