### ISSUE TITLE
Where the db arg comes from in the context? 

### ISSUE THREAD

**Issue by ahsath** [Soluto/graphql-to-mongodb#6]
Hi, can you please provide an example of how to setup the connection to the database or how you do it? a middleware that returns the connected client and the db instance in the context? this is what I did

https://github.com/thebigredgeek/apollo-resolvers/issues/26

**Comment by ShynRou** [comment]
My implenentation with express:
``` javascript
  const MongoClient = mongodb.MongoClient;
  let db;

  try {
    let client = await MongoClient.connect(config.db.url);
    db = client.db(config.db.database);
  } catch (error) {
    console.error(error);
    process.exit(1);
  }

  const app = express();

  app.use('/graphql',
    graphqlHTTP({
        schema: Schema,
        rootValue: {},
        graphiql: true,
        context: { db },
        formatError: (err) => {
          console.log(err);
          return err;
        }
      })
  );
  app.listen(config.server.port);
```

**Comment by ahsath** [comment]
It is safe to pass the db instance even before /graphql?

**Comment by ShynRou** [comment]
Yeah, my init function is async so I use await to make sure the MongoDB connection is established before moving on to initialization.

**Comment by ahsath** [comment]
How do you handle database connection errors to the client?

**Comment by ShynRou** [comment]
I  close the server since it wont work without, and let it restart via forever or pm2 until it reestablishes a connection.
```
   } catch (error) {
    console.error(error);
    process.exit(1);
  }
```

**Comment by soluto-yoav** [comment]
There's no real right or wrong here; it's simply not within the package's scope to decide how you should do this. It also isn't necessary for the DB connection to reside in the context. Once in the resolve callback, you may acquire it however you prefer. 

@ShynRou's implementation is a valid example.
Another example:
```
import connection from '...'

connection.then(db => {
    app.use('/',
        graphqlHTTP({
            context: { db },
            ...
        }));
}).catch(err =>{
    ...
});
```
